services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"