version: '3.8'

services:
  api:
    build: ./Api
    ports:
      - "5000:8080"
    depends_on:
      - rabbitmq

  worker:
    build: ./Worker
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"